// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5JY5VZ_c-iuqic5DkHqMb2mq4U5OBvak',
    appId: '1:831990641827:web:5817097dada9f0e53bbb16',
    messagingSenderId: '831990641827',
    projectId: 'fir-coding-test-123',
    authDomain: 'fir-coding-test-123.firebaseapp.com',
    storageBucket: 'fir-coding-test-123.appspot.com',
    measurementId: 'G-PHL6GETT3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVGn87JW5KAJCWApeffK5V0IW9FCc5u6s',
    appId: '1:831990641827:android:d35a7c4bed24b4163bbb16',
    messagingSenderId: '831990641827',
    projectId: 'fir-coding-test-123',
    storageBucket: 'fir-coding-test-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADGsIBLKzDW6O57E0FK8TjcjGhmazjicg',
    appId: '1:831990641827:ios:fca2f4653a2a27a53bbb16',
    messagingSenderId: '831990641827',
    projectId: 'fir-coding-test-123',
    storageBucket: 'fir-coding-test-123.appspot.com',
    iosClientId:
        '831990641827-cl4um7jpnjik48q3a3uobtvd0hadugcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADGsIBLKzDW6O57E0FK8TjcjGhmazjicg',
    appId: '1:831990641827:ios:fca2f4653a2a27a53bbb16',
    messagingSenderId: '831990641827',
    projectId: 'fir-coding-test-123',
    storageBucket: 'fir-coding-test-123.appspot.com',
    iosClientId:
        '831990641827-cl4um7jpnjik48q3a3uobtvd0hadugcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasetest',
  );
}
